# Generated by Django 4.1.7 on 2023-03-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_description_post_discount_post_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='name',
        ),
    ]
