# Generated by Django 4.1.7 on 2023-03-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_rename_text_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
