# Generated by Django 4.1.7 on 2023-03-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
