# Generated by Django 4.1.7 on 2023-03-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_alter_post_quantity_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
    ]
