# Generated by Django 4.1.7 on 2023-03-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_alter_post_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpost',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
    ]
