# Generated by Django 4.1.7 on 2023-03-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_alter_subpost_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quantity_available',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subpost',
            name='quantity_available',
            field=models.CharField(max_length=100),
        ),
    ]
