# Generated by Django 4.1.7 on 2023-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_baner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baner',
            name='image',
            field=models.ImageField(upload_to='baner'),
        ),
        migrations.AlterField(
            model_name='post',
            name='discount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post'),
        ),
        migrations.AlterField(
            model_name='subpost',
            name='discount',
            field=models.CharField(max_length=100),
        ),
    ]
